version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: schemars
    versions:
    - 0.8.2
  - dependency-name: serde
    versions:
    - 1.0.122
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
  - dependency-name: log
    versions:
    - 0.4.13
  - dependency-name: yaserde_derive
    versions:
    - 0.5.1
  - dependency-name: yaserde
    versions:
    - 0.5.1
  - dependency-name: mcai_worker_sdk
    versions:
    - 0.11.10
