[package]
name = "dash_manifest_worker"
version = "0.1.0"
authors = ["Marc-Antoine Arnaud <arnaud.marcantoine@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
futures = "0.1.14"
hyper = "0.12"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
simple_logger = "1.0.1"
amqp_worker = "0.1.4"
xml-rs = "0.8.0"
yaserde = "0.3.3"
yaserde_derive = "0.3.5"