[package]
name = "dash_manifest_worker"
version = "0.2.0"
authors = [
  "Marc-Antoine Arnaud <arnaud.marcantoine@gmail.com>",
  "Valentin Noel <valentin.noel@media-io.com>"
]
edition = "2018"

[dependencies]
amqp_worker = "0.6.0"
futures = "0.1.14"
hyper = "0.12"
log = "0.4.6"
serde = "^1.0"
serde_json = "^1.0"
xml-rs = "0.8.0"
yaserde = "0.3.7"
yaserde_derive = "0.3.7"